name: 'Deploy Billar APP on GitHub Pages'

on:
  pull_request:
    branches:
      - production
jobs:
  test:
    uses: ./.github/workflows/test.yml
  push_on_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Get Package Version
        id: get_version
        run: echo "::set-output name=version::$(cat package.json | jq -r .version)"

      - name: Install dependencies
        run: npm install --production

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ghcr.io/nandawtek/billar-app:${{ steps.get_version.outputs.version }}
